### ISSUE TITLE
Content Submission

### ISSUE THREAD

**Issue by jared10fw** [hilarysk/shonda-ipsum#4]
"Don’t let what he wants eclipse what you need. He's very dreamy, but he's not the sun. You are."

"Failure is inevitable, Unavoidable. But failure should never get the last word. You have to hold on to what you want. You have to not take “No” for an answer, and take what’s coming to you. Never give in. Never give up. Stand up. Stand up and take it."

**Comment by hilarysk** [comment]
Thanks for submitting! I'll try to get this added this week.
